# Generated by Django 2.1.4 on 2019-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('img', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('base_link', models.TextField()),
            ],
        ),
    ]
